export const bannersInfo = [
  {
    title: "Academy",
    cities: ["Алматы", "Астана"],
    text: "slide-1-description",
    variant: "btn",
    imgUrl: "/bg.mov",
    video: true,
    id: "Main",
  },
  {
    title: "Fitness Lounge",
    cities: ["Алматы", "Астана"],
    text: "Премиальные фитнесс залы для девушек, которые предоставляют услуги массажа и Spa, помогающие максимально использовать потенциал тренировок.",
    variant: "text",
    imgUrl: "/images/main/bg2_2.jpg",
    activeCity: "",
    id: "Fitness_Lounge",
  },
  {
    title: "Academy.GO",
    cities: ["Алматы", "Астана"],
    text: "Премиальные фитнесс залы для девушек, которые предоставляют услуги массажа и Spa, помогающие максимально использовать потенциал тренировок.",
    variant: "btn",
    imgUrl: "/images/main/bg2_3.jpg",
    id: "Academy_go",
  },
  {
    title: "Academy.XL",
    cities: ["Алматы", "Астана"],
    text: "Премиальные фитнесс залы для девушек, которые предоставляют услуги массажа и Spa, помогающие максимально использовать потенциал тренировок.",
    variant: "text",
    imgUrl: "/images/main/bg2_4.jpg",
    id: "Academy_XL",
  },
  {
    title: "Academy+",
    text: "Премиальные фитнесс залы для девушек, которые предоставляют услуги массажа и Spa, помогающие максимально использовать потенциал тренировок.",
    variant: "block",
    imgUrl: "/images/main/bg2_5.jpg",
    id: "Academy+",
  },
  {
    title: "Academy Online",
    cities: [],
    text: "Премиальные фитнесс залы для девушек, которые предоставляют услуги массажа и Spa, помогающие максимально использовать потенциал тренировок.",
    variant: "text",
    imgUrl: "/images/main/bg2_6.jpg",
    id: "Academy_Online",
  },
  {
    title: "Персональный тренер Academy",
    cities: ["Алматы", "Астана"],
    text: "Премиальные фитнесс залы для девушек, которые предоставляют услуги массажа и Spa, помогающие максимально использовать потенциал тренировок.",
    variant: "btn",
    imgUrl: "/images/main/bg2_7.jpg",
    id: "Personal_training",
  },
];
