export const bannersInfoSlider = [
  [
    {
      title: "IT-COMM",
      cities: [],
      text: "УСЛУГИ ТЕЛЕКОММУНИКАЦИЙ<br/>И СИСТЕМНОЙ ИНТЕГРАЦИИ",
      variant: "btn",
      imgUrl: "/images/main/red_planet.png",
      // video: true,
      id: "it_comm",
      subTitle: "",
      address: "Караганда, ул. Мустафина 9/2, оф.210",
    },
  ],
  [
    {
      title: "Услуги",
      text: "slide-1-description",
      variant: "btn",
      imgUrl: "/images/main/bg2_2.jpg",
      video: true,
      id: "Main",
      subTitle: "01",
    },
  ],
  [
    {
      title: "Наши клиенты",
      cities: ["Алматы", "Астана"],
      text: "Премиальные фитнесс залы для девушек, которые предоставляют услуги массажа и Spa, помогающие максимально использовать потенциал тренировок.",
      variant: "btn",
      imgUrl: "/images/main/bg2_3.jpg",
      id: "Academy_go",
      subTitle: "03",
    },
    {
      title: "Academy.GO",
      cities: ["Алматы", "Астана"],
      text: "Премиальные фитнесс залы для девушек, которые предоставляют услуги массажа и Spa, помогающие максимально использовать потенциал тренировок.",
      variant: "btn",
      imgUrl: "/images/main/bg2_3.jpg",
      id: "Academy_go",
      subTitle: "03",
    },
  ],
  [
    {
      title: "Оставить заявку",
      cities: ["Алматы", "Астана"],
      text: "Премиальные фитнесс залы для девушек, которые предоставляют услуги массажа и Spa, помогающие максимально использовать потенциал тренировок.",
      variant: "text",
      imgUrl: "/images/main/bg2_4.jpg",
      id: "Academy_XL",
      subTitle: "04",
    },
    {
      title: "Academy.XL",
      cities: ["Алматы", "Астана"],
      text: "Премиальные фитнесс залы для девушек, которые предоставляют услуги массажа и Spa, помогающие максимально использовать потенциал тренировок.",
      variant: "text",
      imgUrl: "/images/main/bg2_4.jpg",
      id: "Academy_XL",
      subTitle: "04",
    },
    {
      title: "Контакты",
      cities: ["Алматы", "Астана"],
      text: "Премиальные фитнесс залы для девушек, которые предоставляют услуги массажа и Spa, помогающие максимально использовать потенциал тренировок.",
      variant: "text",
      imgUrl: "/images/main/bg2_4.jpg",
      id: "Academy_XL",
      subTitle: "04",
    },
  ],
  [
    {
      title: "Контакты",
      text: "Премиальные фитнесс залы для девушек, которые предоставляют услуги массажа и Spa, помогающие максимально использовать потенциал тренировок.",
      variant: "block",
      imgUrl: "/images/main/bg2_5.jpg",
      id: "Academy+",
      subTitle: "05",
    },
    {
      title: "Academy+",
      text: "Премиальные фитнесс залы для девушек, которые предоставляют услуги массажа и Spa, помогающие максимально использовать потенциал тренировок.",
      variant: "block",
      imgUrl: "/images/main/bg2_5.jpg",
      id: "Academy+",
      subTitle: "05",
    },
  ],
  // [
  //   {
  //     title: "Корп. клиентам",
  //     cities: [],
  //     text: "Премиальные фитнесс залы для девушек, которые предоставляют услуги массажа и Spa, помогающие максимально использовать потенциал тренировок.",
  //     variant: "text",
  //     imgUrl: "/images/main/bg2_6.jpg",
  //     id: "Academy_Online",
  //     subTitle: "06",
  //   },
  //   {
  //     title: "Academy Online",
  //     cities: [],
  //     text: "Премиальные фитнесс залы для девушек, которые предоставляют услуги массажа и Spa, помогающие максимально использовать потенциал тренировок.",
  //     variant: "text",
  //     imgUrl: "/images/main/bg2_6.jpg",
  //     id: "Academy_Online",
  //     subTitle: "06",
  //   },
  // ],
  // [
  //   {
  //     title: "Онлайн-тренировки",
  //     cities: ["Алматы", "Астана"],
  //     text: "Премиальные фитнесс залы для девушек, которые предоставляют услуги массажа и Spa, помогающие максимально использовать потенциал тренировок.",
  //     variant: "btn",
  //     imgUrl: "/images/main/bg2_7.jpg",
  //     id: "Personal_training1",
  //     subTitle: "07",
  //   },
  // ],
  // [
  //   {
  //     title: "Интернет-магазин",
  //     cities: ["Алматы", "Астана"],
  //     text: "Премиальные фитнесс залы для девушек, которые предоставляют услуги массажа и Spa, помогающие максимально использовать потенциал тренировок.",
  //     variant: "btn",
  //     imgUrl: "/images/main/bg2_7.jpg",
  //     id: "Personal_training2",
  //     subTitle: "08",
  //   },
  // ],
  // [
  //   {
  //     title: "Academy+ app",
  //     cities: ["Алматы", "Астана"],
  //     text: "Премиальные фитнесс залы для девушек, которые предоставляют услуги массажа и Spa, помогающие максимально использовать потенциал тренировок.",
  //     variant: "block",
  //     imgUrl: "/images/main/bg2_7.jpg",
  //     id: "Personal_training3",
  //     subTitle: "09",
  //   },
  // ],
  // [
  //   {
  //     title: "Франшиза",
  //     cities: [],
  //     text: "Премиальные фитнес залы для девушек, которые предоставляют услуги массажа и Spa, помогающие максимально использовать потенциал тренировок.",
  //     variant: "btn",
  //     imgUrl: "/images/main/bg2_7.jpg",
  //     id: "Франшиза",
  //     subTitle: "10",
  //   },
  // ],
];
